server:
  port: ${SERVER_PORT:8080}

spring:
  http:
    encoding:
      force-response: true

app:
  url: ${DB_URL:jdbc:oracle:thin:@localhost:1521:XE}
  username: ${DB_USERNAME:system}
  password: ${DB_PASSWORD:oracle}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
